# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [ ]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
import NumPy as np
list_1 = [6,8,40,80,200,679,800,1289]
list_1

In [ ]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

In [ ]:
type(my_numpy_array)

In [ ]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2,5,8],[3,7,9]])
print(my_matrix)
type(my_matrix)

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
array_matrix = np.array([[3,7,9,3],
                        [4,3,2,2]])
print(array_matrix)

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [ ]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
y = np.random.rand(3,3)
y

In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows
z = np.random.randint(1,50)
print(z)
a = np.random.randint(1,40,9)
print(a)

In [ ]:
# np.arange creates an evenly spaced values within a given interval
b = np.arange(1,50,5)
print(b)
c = np.arange(1,20)
c

In [ ]:
# create a diagonal of ones and zeros everywhere else
d = np.eye(4)
d

In [ ]:
# Matrix of ones
e = np.ones((7,3))
e

In [ ]:
# Array of zeros
f = np.zeros((8,2))
f

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Enter the number for the range: "))
g = np.random.randint(0,x,10)
print(g)

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
h = np.arange(1,9,2)
print(h)
i = np.arange(1,9,2)
print(i)



In [ ]:
# Add 2 numpy arrays together
j = h+i
print(j)

In [ ]:
k = h**i
print(k)

In [ ]:
l = h**2
print(l)
m = np.sqrt(l)
print(m)

In [ ]:
n = np.exp(i)
print(n)

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
x = np.array([5,7,10])
print(x)
y = np.array([9,15,4])
print(y)
z = np.array(x-y)
print(z)
p = x-y
print(p)

Q = np.sqrt(x**2 +  y**2)
print(Q)

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [ ]:
num_py_array = np.array([5,7,8,2,6,10,16,25,67,89])
print(num_py_array)

In [ ]:
# Access specific index from the numpy array
num_py_array[4]
num_py_array[-1]

In [ ]:
# Starting from the first index 0 up until and NOT including the last element
num_py_array[0:-1]

In [ ]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4]= 7
print(my_numpy_array)

In [ ]:
# Let's define a two dimensional numpy array
matrix_numpy = np.random.randint(1,10,(4,4))
print(matrix_numpy)

In [ ]:
# Get a row from a mtrix
print(matrix_numpy[0])
print(matrix_numpy[-1])

In [ ]:
# Get one element
print(matrix_numpy[0][3])
print(matrix_numpy[2][1])

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [ ]:
x = np.array([[2, 30, 20, -2, -4],[3, 4,  40, -3, -2],[-3, 4, -6, 90 ,10],[25, 45, 34, 22, 12],
              [13 ,24, 22, 32, 37]])
print(x)
print(x[-1])
x[-1]=0
print(x)

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [ ]:
A = np.random.randint(1,100,(5,5))
print(A)

In [ ]:
B = A[A > 4]
print(B)



In [ ]:
# Obtain odd elements only
C = A[A % 2 ==1]
print(C)

D = A[A % 2 != 0]
print(D)

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
x = np.array([[2, 30, 20, -2, -4],[3, 4,  40, -3, -2],[-3, 4, -6, 90 ,10],[25, 45, 34, 22, 12],
              [13 ,24, 22, 32, 37]])
print(x)
x[x < 0]=0
print(x)


x[x%2!=0] = -2
print(x)

